# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
BulkDiscount.destroy_all

BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 1)
BulkDiscount.create(percentage: 0.05, threshold: 2, merchant_id: 1)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 2)
BulkDiscount.create(percentage: 0.05, threshold: 2, merchant_id: 3)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 4)
BulkDiscount.create(percentage: 0.05, threshold: 2, merchant_id: 5)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 6)
BulkDiscount.create(percentage: 0.05, threshold: 2, merchant_id: 7)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 8)
BulkDiscount.create(percentage: 0.05, threshold: 3, merchant_id: 9)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 10)
BulkDiscount.create(percentage: 0.05, threshold: 2, merchant_id: 11)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 12)
BulkDiscount.create(percentage: 0.05, threshold: 2, merchant_id: 13)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 14)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 15)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 16)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 17)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 18)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 19)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 20)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 21)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 22)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 23)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 24)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 25)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 26)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 27)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 28)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 29)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 30)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 31)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 32)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 33)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 34)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 35)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 36)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 37)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 38)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 39)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 40)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 51)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 52)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 53)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 54)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 55)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 56)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 57)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 58)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 59)
BulkDiscount.create(percentage: 0.1, threshold: 4, merchant_id: 60)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 1)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 2)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 3)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 4)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 5)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 6)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 7)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 8)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 9)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 10)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 11)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 12)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 13)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 14)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 15)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 16)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 17)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 18)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 19)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 20)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 21)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 22)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 23)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 24)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 25)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 26)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 27)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 28)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 29)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 30)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 31)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 32)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 33)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 34)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 35)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 36)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 37)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 38)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 39)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 40)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 51)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 52)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 53)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 54)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 55)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 56)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 57)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 58)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 59)
BulkDiscount.create(percentage: 0.3, threshold: 10, merchant_id: 60)


x = BulkDiscount.joins(merchant: [{ items: [{invoices: :invoice_items}]}]).where(merchants: {id: 1}, invoice_items: {invoice_id:882}).where('invoice_items.quantity >= bulk_discounts.threshold').select('invoice_items.id AS invoice_item_id', 'invoice_items.quantity', 'bulk_discounts.id AS discount_id', 'items.id AS item_id').distinct

x = BulkDiscount.joins(merchant: [{ items: [{invoices: :invoice_items}]}]).where(merchants: {id: 1}, invoice_items: {invoice_id: 882, id: 3928}).where('invoice_items.quantity >= bulk_discounts.threshold').select('invoice_items.id AS invoice_item_id', 'invoice_items.quantity', 'bulk_discounts.threshold', 'bulk_discounts.id AS discount_id', 'items.id AS item_id').order('bulk_discounts.threshold DESC').take

link_to_if(ii.applied_discount(@merchant.id) != nil, 'Discount', { controller: "merchant/bulk_discounts", action: "show" })
